### ISSUE TITLE
Simulationsergebnisse sind unrealistisch positiv

### ISSUE THREAD

**Issue by DDvO** [nick81nrw/PVTools#11]
In einem [Abschnitt meiner Solarinfo-Seite](https://ddvo.github.io/Solar/#PVTool) kommentiere ich euer Tool wie folgt:

Eine sehr einfache Möglichkeit, online die Amortisation zu berechnen, bietet
auch das [PVTool von „AkkuDoktor“](https://www.akkudoktor.net/pvtool-rechner/).
Als Besonderheit kann man hier schön sehen, wie sich Eigenverbrauchsquote,
Autarkiegrad und Amortisation in Abhängigkeit von der Anwesenheit und Kapazität
eines Stromspeichers ändern.

Für Speicher wird stillschweigend und nicht änderbar AC-Kopplung angenommen.
Leider sind die Ergebnisse v.A. ohne Speicher und bei kleineren Speichergrößen
deutlich zu optimistisch. Dafür gibt es (mindestens) folgende Gründe:
* Vor Allem wird das [Standard-Haushalts-Lastprofil H0 des VDEW](
https://www.bdew.de/energie/standardlastprofile-strom/) (inzwischen: BDEW)
  von 1996/97 verwendet, und das auch nur in Stundenauflösung
  statt in der verfügbaren 15-minütigen Auflösung.
  Damit können keinerlei Lastspitzen berücksichtigt werden,
  wozu mindestens Minutenauflösung (besser: Sekundenauflösung) benötigt wird.\
  Leider kann man auch kein eigenes (individuelles) Lastprofil verwenden.
* Es werden keine Speicherverluste berücksichtigt.
* Die Lade- und Entlade-Wirkungsgrade für den Speicher werden standardmäßig
  unrealistisch hoch angenommenen,
  was man aber in den erweiterten Einstellungen anpassen kann.
* Standardmäßig wird die Lade- und Entladeleistung nicht begrenzt,
  wobei man das ebenfalls in den erweiterten Einstellungen korrigieren kann.

**Comment by nick81nrw** [comment]
Hi, ich hatte deinen Beitrag schon mal gelesen, ich finde es gut das du verschiedene Lösung miteinander vergleichst 👍

Aber zu deinen Punkten:

- Es geht leider nur eine Stundenauswertung, da wir als "PV-Erzeugungs-Quelle" die Daten von PVGis verwenden. Dort gibt es nur eine stundenweise PV-Erzeugung. Auch die TMY Werte sind nur stundengenau. Das SPL könnte man auch im 15Min Takt berechnen, aber wenn die Erzeugung nicht genauer vorliegt, bringen mir die Daten leider keinen Mehrwert. Somit hast du völlig recht, Lastspitzen werden nicht berücksichtigt. Die Überlegung war, gewisse Lastspitzen mit einer theoretischen Annahme "rauszurechnen" und ggfls. vom User anpassbar zu gestalten. Aber mir fehlte da die entscheidende Idee, welche Werte sinnvoll sind. 
- Speicherverluste bzw. Ladeeffizienzen werden berücksichtigt und können angepasst werden. Findest du unter "Erweiterte Einstellungen". Damit kannst du beides steuern.
![image](https://user-images.githubusercontent.com/79307089/235437817-d5f7ec74-ddbf-48d6-bb5e-f1a9503abb3e.png)
- Welche Werte hältst du denn für angebracht im Standard vorzugeben?

**Comment by DDvO** [comment]
Super, dass du gleich auf meine Punkte reagiert hast :+1: 
Erst mal zu den verschiedenen Arten von Verlusten, denn das geht schneller zu beantworten:

Es ist sinnvoll, auch Ladeverluste (also die Effizienz der Laderegelung) und Speicherverluste (also das was, nach dem Laden innerhalb des Speichers verloren geht) getrennt zu betrachten und dann konsequenterweise auch die Speicherverluste einstellbar zu machen. 

Denn es macht einen (wenn auch nicht sehr großen) Unterschied, ob und und welcher Höhe (nach der Verringerung der Brutto-Ladeleistung durch die Ladeverluste) die Netto-Ladeleistung noch (wie in den erweiterten Optionen einstellbar) begrenzt wird und/oder die nutzbare Speicherkapazität die aktuelle Ladeleistung begrenzt, weil der Speicher gerade voll wird.
Erst danach werden die Speicherverluste relevant, 
und bei der Entladung kommt erst nach den Begrenzungen durch die minimale Entladetiefe und die maximale Entladeleistung die Entlade-Effizienz zum Tragen, also für die (bei AC-Kopplung erneute) Wechselrichtung des aus dem Speicher tatsächlich entnommenen Stroms.

Also sollte man alle drei Arten von Verlusten auseinanderhalten. 

So macht es auch die HTW Berlin, siehe unter dem Stichwort "Berechnungsgrundlagen" in https://solar.htw-berlin.de/faq-unabhaengigkeitsrechner/, und setzt folgende Werte an:
* Ladewirkungsgrad 94%
* Speicherwirkungsgrad 95%
* Entladewirkungsgrad 94%



Wie auf meiner Solarinfo-Seite geschrieben, verwende ich diese Werte ebenfalls
und empfehle sie als Defaults auch für euren Simulator.

**Comment by DDvO** [comment]
Und zum Thema Auflösung der PV- und Last-Daten:

Ich kenne leider auch keine Quelle von PV-Ertragsdaten, die man für beliebige Standorte und frei wählbare Modul-Ausrichtungen kostenlos abrufen könnte und eine bessere Auflösung bietet als die Stunden-Auflösung von PVGIS.
Aber die Auflösung der PV-Daten (und damit PV-Ertragsspitzen) ist eine andere Geschichte als die der Last-Daten (und damit Lastspitzen).

Selbst wenn man die PV-Daten nur in Stundenauflösung hat, macht es einen erheblichen Unterschied, wie hoch die Lastdaten aufgelöst sind, und der Unterschied für den Eigenverbrauch und ggf. den Gewinn durch einen Speicher ist bei der Last größer, weil die Last meist viel stärker schwankt als die PV-Leistung.

Wenn man immerhin die Lastspitzen wenigstens einigermaßen berücksichtigen kann, fallen die Ergebnisse für den Eigenverbrauch realistischerweise deutlich geringer aus, weil es recht oft passiert, dass Lastspitzen durch die aktuelle PV-Leistung (und ggf. nicht mal durch eine begrenzte Speicher-Entladeleistung) abgefangen werden können.

Hier mal ein Vergleich mit dem SolBatSim für eine PV-Simulation  bei sonst gleichen Daten, insbesondere
```
Verbrauch durch Haushalt    = 3000 kWh
PV-Nominalleistung          = 1000 Wp
```
mit dem selben Lastprofil in stündlicher, minütlicher und fast sekündlicher (etwa 2400 Datenpunkte pro Stunde) Auflösung:
```
PV-Eigenverbrauch           =  809 kWh
Netzeinspeisung             =  285 kWh

PV-Eigenverbrauch           =  747 kWh
Netzeinspeisung             =  347 kWh

PV-Eigenverbrauch           =  735 kWh
Netzeinspeisung             =  359 kWh
```

**Comment by nick81nrw** [comment]
sollte jetzt korrigiert sein. Siehe Video von Andreas
https://www.youtube.com/watch?v=BWBkrNMinAo

**Comment by DDvO** [comment]
Gut, dass ihr das nun verbessert habt!
Allerdings komme ich beim Testen mit der aktuellen Version des PVTools immer noch auf recht hoch anmutende Ergebnisse.

Bei 3000 kWh Jahresverbrauch, 1000 Wp mit optimaler Ausrichtung ohne Speicher im Raum München komme ich für ein typisches meteorologisches Jahr aus 2005..2020 mit dem [SolBatSim](https://github.com/DDvO/SolBatSim) bei meinem Standard-Lastprofil mit minütlicher Auflösung auf etwa 611 kWh Eigenverbrauch und 490 kWh Netzeinspeisung.
Mit dem PVTool hingegen auf: Selbstgenutzter Strom 741.85 kWh, Eingespeister Strom 431.71 kWh.

Der zugrundeliegende PV-Bruttoertrag ist (wie zu erwarten) einigermaßen gleich: 1273 kWh vs. 1228.6 kWh.
Der PV-Nettoertrag (nach System- und WR-Verlusten) ist bei mir allerdings 1101 kWh, bei euch recht hoch: 1173,3 kWh.
Offenbar liegt ein Teil der Erklärung der noch vorhandenen Unterschiede in den angenommenen Wirkungsgraden.

**Comment by DDvO** [comment]
Danke auch für den Hinweis auf das [Video von Andreas](https://www.youtube.com/watch?v=BWBkrNMinAo).

Tut mir leid zu hören, dass ihr durch Reaction-Videos so blöde Anschuldigungen bekommen habt.

Interessant, dass das von der HTW Berlin verwendete Jahr 2017 für die dortige Region ein recht ungünstiges, als nicht repräsentatives, PV-Jahr war. Allerdings war es z.B. für den Raum München fast durchschnittlich gut.

Die Erklärung von Andreas, wieso die Simulation mit nur stündlichen Last-Daten zu viel zu positiven Ergebnissen führt, war recht schwach und teils irreführend. Die richtige Erklärung hat nämlich nichts mit Kommutativität der Summation und roten Balken zu tun und nur wenig mit der Leistungs-Begrenzung durch Wechselrichter, sondern es liegt v.A. daran, dass zum einen insgesamt leistungsschwache PV-Anlage kurzzeitige Spitzenlasten nicht abdecken kann und zum anderen Balkonkraftwerke zeitweisen Überschuss ins externe Netz verschenken, weshalb es unrealistisch positiv aussieht, wenn man nur stündliche Mittelwerte betrachtet.

**Comment by DDvO** [comment]
Bitte den issue wieder öffnen, weil jedenfalls nicht alle angesprochenen Probleme gelöst sind.

**Comment by DDvO** [comment]
Wenn ich das Video richtig verstanden habe, verwendet ihr nun für jede Stunde eine synthetisierte Lastverteilung im 10-Sekunden-Raster?
Und welche stündliche Lastverteilung verwendet ihr nun - weiterhin das BDEW-Standardlastprofil H0 von 1996/97?

**Comment by DDvO** [comment]
Nachdem die Unterschiede zumindest am Simulationsjahr und dem angenommenen Wirkungsgrad liegen müssen,
hier noch die Ergebnisse für das Jahr 2017, welches im Raum München recht durchschnittlich war, und gleichem Gesamt-Wirkungsgrad 86,48% (PV-System 92%, Wechselrichter 94%):

Bei 3000 kWh Jahresverbrauch, 1000 Wp mit optimaler Ausrichtung ohne Speicher im Raum München komme ich für das Jahr 2017 mit dem [SolBatSim](https://github.com/DDvO/SolBatSim) bei meinem Standard-Lastprofil mit minütlicher Auflösung auf etwa 607 kWh Eigenverbrauch und 481 kWh Netzeinspeisung.
Mit dem PVTool hingegen nach Eingabe von 13,52% Systemverlust auf: Selbstgenutzter Strom 687.35 kWh, Eingespeister Strom 352.42 kWh

Der zugrundeliegende PV-Bruttoertrag ist (wie zu erwarten) nun so gut wie gleich: 1259 kWh vs. 1260.4  kWh.
Der PV-Nettoertrag (nach System- und jedenfalls bei mir auch WR-Verlusten) ist nun ebenfalls so gut wie gleich: 1089 kWh vs. 1090,0 kWh.

Damit liegen die verbleibenden Diskrepanzen wohl nicht an den PV-Daten und angenommenen Wirkungsgraden,
sondern offenbar am Lastprofil. In der Tat, wenn ich ein anderes Lastprofil  (in dem Fall mit Auflösung ca. 1,5 sek) verwende, 
komme ich auf etwa 740 kWh Eigenverbrauch und 349 kWh Netzeinspeisung, also auf ein relativ ähnliches Ergebnis.

Was ich nicht verstehe: Wieso rechnet ihr noch extra Wechselrichter-Verluste von in dem Fall 51,2 kWh?
Und die kann man wohl nicht als Nutzer konfigureren - wie bestimmt ihr die?

**Comment by nick81nrw** [comment]
Moin, ich halte mich bei ein paar Fragen zurück und hoffe das Andreas dazu etwas schreibt. Ein paar Antworten aber von mir:

> Wenn ich das Video richtig verstanden habe, verwendet ihr nun für jede Stunde eine synthetisierte Lastverteilung im 10-Sekunden-Raster?
Nicht ganz. Aus den Datensätzen wurde eine Stündliche Verteilung erstellt. Diese nutze ich als "prozentuale Verteilung" je "Leistungsbereich". Also z.B. 3% in der Stunde wird im Bereich 2500-2600 Watt abgerufen. Hierzu gibt es nun mehrere Leistungsstufen die separat gerechnet werden. In jeder dieser Leistungsstufen rechnen wir "reicht Leistung WR", "Ist die Erzeugung > Verbrauch (Einspeisung?)", "Der WR wird zu 20% belastet, also Wirkungsgrad geringer" etc. und konsolidieren die Ergebnis als "Bilanzierte"-Stunde zusammen. Dabei kommen dann z.B. 25Wh Verluste, 200Wh Eigenverbrauch, 50Wh Verbrauch höher als WR-Leistung, etc. raus.

**Comment by drbacke** [comment]
Genau Nick hat es ganz gut erklärt, wir machen es über diskrete Wahrscheinlichkeitsdichten.
Ein Nachtrag "Kommutativ" das ist nicht schwach erklärt, sondern trifft das Problem sehr gut. 
Wenn du auf der einen Seite der Gleichung den 1h Mittelwert hat und auf der anderen Seite das 1h Mittel aus 10s Werten gebildet, so ist das tatsächlich kommutativ, am Ende kannst du beides exakt ineinander umrechnen und vertauschen wie du willst. Es ist identisch. Sobald du aber durch den Wechselrichter auf der rechten Seite dann an einigen der 10s Terme innerhalb des Mittelwertes die Maximum Funktion hast / eine andere Gewichtung, ist es nicht mehr möglich die Werte beliebig zu vertauschen. 
Über den Begriff kommutativ kann man hier vermutlich streiten, aber im weitesten Sinne halte ich den hier für durchaus zutreffend. Letztlich geht es im Kern um nichts anderes: Die Bildung des Mittelwertes und die Terme der einzelnen Komponenten innerhalb des Mittelwerts.

**Comment by DDvO** [comment]
Danke @nick81nrw für deine (Teil-)Antwort.

Nochmal vorab meine Frage:
Welches stündliche (Durchschnitts-)Lastprofil verwendet ihr inzwischen - 
weiterhin das BDEW-Standardlastprofil H0 von 1996/97, oder welches sonst?

> > Wenn ich das Video richtig verstanden habe, verwendet ihr nun für jede Stunde eine synthetisierte Lastverteilung im 10-Sekunden-Raster?
> 
> Nicht ganz. Aus den Datensätzen wurde eine Stündliche Verteilung erstellt. Diese nutze ich als "prozentuale Verteilung" je "Leistungsbereich". Also z.B. 3% in der Stunde wird im Bereich 2500-2600 Watt abgerufen. Hierzu gibt es nun mehrere Leistungsstufen die separat gerechnet werden.

Erst mal muss für die Simulation das zugrunde gelegte stündliche (Durchschnitts-)Lastprofil, welches ja einen gewissen Jahres-Gesamtverbrauch ergibt, irgendwie auf den vom Nutzer angegebenen Jahresverbrauch skaliert werden.
Ich rechne die vorhandenen Last-Werte einfach linear um - ihr auch?

Ok, ihr nehmt also nicht wie ich erst dachte für jede 10 Sekunden einen skalierten und gemäß Verteilung synthetisierten Last-Wert, sondern teilt das Spektrum in Leistungsstufen ein und verwendet diese anteilig gemäß der Häufigkeitsverteilung.
Das ist nicht ganz so genau, aber deutlich effizienter, weil ihr damit pro Stunde nicht 6*60 Werte simulieren müsst, sondern vermutlich etwa 20-50 Werte, oder? 

Gute Idee - ich sollte meine Lastprofile auch in der Art quantisieren - dann werden sie stark komprimiert und die Simulation geht viel schneller.

> In jeder dieser Leistungsstufen rechnen wir "reicht Leistung WR", "Ist die Erzeugung > Verbrauch (Einspeisung?)", "Der WR wird zu 20% belastet, also Wirkungsgrad geringer" etc. und konsolidieren die Ergebnis als "Bilanzierte"-Stunde zusammen. Dabei kommen dann z.B. 25Wh Verluste, 200Wh Eigenverbrauch, 50Wh Verbrauch höher als WR-Leistung, etc. raus.

Wenn ich das richtig verstehe, vergleicht ihr jede (Last-)Leistungsstufe mit der gemäß Solardaten in der betrachteten Stunde gegeben Erzeugungsleistung. Die Erzeugung wird bis zur Höhe des Verbrauchs als Eigenverbrauch aufsummiert, und alles, was an Erzeugung ggf. über dem Verbrauch liegt, als Netzeinspeisung.
Vorher aber zieht ihr noch (zusätzliche) WR-Verluste ab, die vom Auslastungsgrad des WR abhängig sind  - sehr gut. So eine dynamische Adaption des WR-Wirkungsgrades mache ich (bislang) nicht.

Sind die in den Details angezeigten "Verluste Wechselrichter" die Summe all dieser (zusätzlichen) dynamischen Verluste, oder ist in dieser Zahl auch noch ein fester statischer WR- bzw. MPPT-Verlust enthalten?
Anders gefragt: Was alles betrachtet ihr als zu den Verlusten zugehörig, für die man als Benutzer eine konstante Prozentzahl angeben kann? Wenn ich das weiß, kann ich unsere Ergebnisse genauer vergleichen. 

> Dein Perl Skript scheint einen ähnlichen Ansatz zu verfolgen 👍

Es ist leider nicht so effizient, weil es keine Wahrscheinlichkeitsdichten verwendet, und was die WR-Verluste betrifft nicht so genau.

**Comment by DDvO** [comment]
> Genau Nick hat es ganz gut erklärt, wir machen es über diskrete Wahrscheinlichkeitsdichten. Ein Nachtrag "Kommutativ" das ist nicht schwach erklärt, sondern trifft das Problem sehr gut. Wenn du auf der einen Seite der Gleichung den 1h Mittelwert hast und auf der anderen Seite das 1h Mittel aus 10s Werten gebildet, so ist das tatsächlich kommutativ, am Ende kannst du beides exakt ineinander umrechnen und vertauschen wie du willst. Es ist identisch. Sobald du aber durch den Wechselrichter auf der rechten Seite dann an einigen der 10s Terme innerhalb des Mittelwertes die Maximum Funktion hast / eine andere Gewichtung, ist es nicht mehr möglich die Werte beliebig zu vertauschen. Über den Begriff kommutativ kann man hier vermutlich streiten, aber im weitesten Sinne halte ich den hier für durchaus zutreffend. Letztlich geht es im Kern um nichts anderes: Die Bildung des Mittelwertes und die Terme der einzelnen Komponenten innerhalb des Mittelwerts. Das ist ein einfaches math. Problem, es muss nicht mal physikalisch erklärt werden.

Nach der Erklärung von NIck zur Nutzung der Wahrscheinlichkeitsdichten verstehe ich, warum du von "kommutativ" sprichst. Aber die (Nicht-)Kommutätivität kommt nur durch eure Optimierung unter Verwendung der Wahrscheinlichkeitsdichten ins Spiel. Und auch unabhängig davon bräuchte man für die Vergleichbarkeit auch noch die Assoziativität.
Aber der entscheidende Punkt ist eigentlich ein anderer: über die Vergleiche bzw. die max/min-Bildung kommt Nichtlinearität ins Spiel, so dass die Summe der Teile in den verschiedenen Akkumulatoren (Eigenverbrauch, Netzeinspeisung u.ä.) anders ist als die Aufteilung nach vorheriger Summierung (Mittelwert).
Ich hatte es oben  so ausgedrückt:

> es liegt v.A. daran, dass zum einen eine leistungsschwache PV-Anlage kurzzeitige Spitzenlasten nicht abdecken kann und zum anderen Balkonkraftwerke zeitweisen Überschuss ins externe Netz verschenken, weshalb es unrealistisch positiv aussieht, wenn man nur stündliche Mittelwerte betrachtet.

Ich meine, dass so eine Erklärung direkter, sogar noch treffender und für die Zuhörer einfacher zu verstehen wäre - oder @drbacke was denkst du?

**Comment by DDvO** [comment]
Super, dass man mit eurem PVTool inzwischen auch ein eigenes Lastprofil verwenden kann.

Etwas Feedback zur Syntax habe ich auf https://github.com/nick81nrw/PVTools/issues/36 gegeben.

Wunderbar, damit können wir die Ausgaben unserer Tools mit (so gut wie) identischen Eingabe-Daten vergleichen!
Ich hänge hier mal ein Beispiel-Lastprofil (mit 5860,8 kWh Jahresverbrauch) in Stundenauflösung an:
[Lastprofil_00-std-PVTool.csv](https://github.com/nick81nrw/PVTools/files/13697726/Lastprofil_00-std-PVTool.csv)
für das ich auch sehr hohe Auflösung im Raster von ca. 1,5 Sekunden habe.

Damit bekomme ich mit dem SolBatSim für meinen Beispiel-Standort "Speichersee" (nordöstlich von München)
für das Jahr 2017 bei 1000 Wp, Neigungswinkel 38°, Azimut 0° , 
92% System-Wirkungsgrad und 94% WR-Wirkungsgrad Folgendes:
```
PV-Bruttoertrag             = 1259 kWh
PV-DC-Ertrag                = 1158 kWh, PV-System-Wirkungsgrad 92%
PV-Nettoertrag              = 1089 kWh bei Wechselrichter-Wirkungsgrad 94%

Verbrauch                   = 5861 kWh
PV-Eigenverbrauch           =  955 kWh
Netzeinspeisung             =  134 kWh
PV-Eigenverbrauchsanteil    =   88 % des PV-Nettoertrags (Nutzungsgrad)
Eigendeckungsanteil         =   16 % des Verbrauchs (Autarkiegrad)
```

Mit dem PVTool hingegen:

Selbstgenutzter Strom / Jahr 840.84 kWh	
Eingespeister Strom / Jahr 207.41 kWh	
Eigenverbrauchsquote 75.86 %	
Autarkiegrad 14.35 %	

PV Erzeugung 	1108.5 kWh	
Stromverbrauch  5860.9 kWh	
Netzbezug 5020.1 kWh	
Fehlende??? Netzeinspeisung  0.0 kWh	
Verluste Wirkungsgrad Wechselrichter 62.7 kWh	
Verluste PV-Leistung > Wechelrichter Leistung ???  0.0 kWh	
	
Wenn man die WR-Verluste relativ zu (1108.5 kWh  + 62.7 kWh) ausdrückt, kommt man auf einen durchschnittlichen Verlust von 5,35%, was recht gut zu dem von mir (leider nur pauschal) angesetzten Verlust von 6% passt.

Hmm, also zumindest eines unserer Tools simuliert falsch.


Wenn man mal zum Vergleich eine PV-Leistung von 5 kWp nimmt,
kommt der SolBatSim auf
```
PV-Eigenverbrauch           = 2332 kWh
Netzeinspeisung             = 3112 kWh
```
und das PVTool auf 

Selbstgenutzter Strom / Jahr 1832.35 kWh
Eingespeister Strom / Jahr  3541.96 kWh
Verluste Wirkungsgrad Wechselrichter  136.8 kWh (also 2,4%)

Auch hier sind die Differenzen zwischen den Ergebnissen so groß, 
dass sie nicht mit den (angenommenen/teils berechneten) Verlusten erklärt werden können.

Interessanterweise haben wir jedenfalls bei diesem Lastprofil (im Gegensatz zu früher)
das Phänomen, dass der SolBatSim positivere Ergebnisse bringt als das PVTool.

**Comment by drbacke** [comment]
Ich glaube, dass die Kommutativ Diskussion nicht sehr zielführend ist. Im Nachhinein fällt einem oft etwas ein, was man besser erklären könnte. Nur dann ist es halt zu spät ^^ So wichtig ist das letztlich auch nicht. 
Ich hab das eher auf die max() Funktion bezogen, also das im Inneren quasi der Teil ist, den ich gerne auflösen würde. Ist vermutlich relativ unglücklich erklärt. Passiert. 

Zu den Ergebnissen:
Die Summen / Unterschiede finde ich jetzt nicht so groß. Kannst du denn an den Monatswerten / der Datenausgabe erkennen, wo die Differenzen genau herkommen? 
Selbst mit gleichem Lastprofil, haben wir vermutlich (durch die Verteilungen) immer noch eine andere Aufteilung der Lasten/10s Problematik. Es ist kaum zu erwarten, dass die Ergebnisse so exakt übereinstimmen, wäre aber gut zu wissen woher die Unterschiede kommen. Dann wüsste man es zumindest. 

Vor einiger Zeit war mal ein Bug drin, dass der Januar etwas komisch vorhergesagt wurde. Ich bin unsicher, ob wir den Bug gefixt haben. Deswegen wären die Monatswerte spannend.

**Comment by DDvO** [comment]
> Die Summen / Unterschiede finde ich jetzt nicht so groß. Kannst du denn an den Monatswerten / der Datenausgabe erkennen, wo die Differenzen genau herkommen?

Auf Anhieb nicht, sonst hätte ich dazu gleich was geschrieben.
Sehr hilfreich fürs Debugging ist, wenn man die Simulation auf einen kurzen Zeitabschnitt einschränken kann.
Beim SolBatSim kann man das sehr flexibel machen, z.B. nur für ein Monats oder Tag oder auch nur ne Stunde oder auch für Intervalle davon, mit folgender Option:
```
[-only <*|year[..year]>[-<*|mon[..mon]>[-<*|day[..day]>[:<*|hour[..hour]]]]]
```
Außerdem kann man sich bei Bedarf im Detail tracen lassen, was in der Simulation passiert,
und die Ergebnisse auf Jahreszeiten, Monate, Wochen, Tage und Stunden aufgesplittet ausgeben lassen:
```
[-hour <statistics file>] [-day <stat file>] [-week <stat file>] [-month <stat file>] [-season <file>] [-max <stat file>]
```
Habt ihr beim PVTool zumindest intern auch solche Diagnose-Möglichkeiten?

Ich hatte gestern Abend immerhin schon mal einen trivialen sanity check gemacht und ein Lastprofil als Test verwendet, das für jede Zeit die Last 0 beinhaltet.
Der SolBatSim kommt dann sinnigerweise zu dem Ergebnis, dass der ganze PV-Nettoertrag in die Netzeinspeisung geht,
während das PVTool damit nicht ganz klarkommt und als `Eingespeister Strom / Jahr` nur `NaN kWh` ausgibt.


> Selbst mit gleichem Lastprofil, haben wir vermutlich (durch die Verteilungen) immer noch eine andere Aufteilung der Lasten/10s Problematik. Es ist kaum zu erwarten, dass die Ergebnisse so exakt übereinstimmen, wäre aber gut zu wissen woher die Unterschiede kommen. Dann wüsste man es zumindest.

Richtig, da wird es im Detail immer noch Unterschiede geben, aber die sind schon bei den zwei o.g. Beispielen schon recht groß, so dass man sich schon fragen muss, ob das nur an anders angenommenen Ausschlägen der Last innerhalb der Stunden liegt.

Als Zwischenschritt wäre schon mal sinnvoll zu vergleichen, wie eure Ergebnisse sind, wenn ihr nur den Stunden-Mittelwert der Last nehmt, sprich die neue Geschichte mit den diskreten Wahrscheinlichkeitsdichten probeweise abschaltet.
Ich kann beim SolBatSim jedenfalls ganz einfach auch mit platten Stundenwerten rechnen und komme damit für sonst gleiche Parameter auf:
```
PV-Bruttoertrag             = 6295 kWh
PV-DC-Ertrag                = 5792 kWh, PV-System-Wirkungsgrad 92%
PV-Nettoertrag              = 5444 kWh bei Wechselrichter-Wirkungsgrad 94%

Verbrauch                   = 5861 kWh
PV-Eigenverbrauch           = 2534 kWh
Netzeinspeisung             = 2910 kWh
PV-Eigenverbrauchsanteil    =   47 % des PV-Nettoertrags (Nutzungsgrad)
Eigendeckungsanteil         =   43 % des Verbrauchs (Autarkiegrad)
```
