### ISSUE TITLE
Fixkosten für Akku

### ISSUE THREAD

**Issue by kriede** [nick81nrw/PVTools#13]
Oft fallen für ein PV-Anlage mit Akku gegenüber ohne Akku einmalige Kosten an. So gibt es Akku-Systeme mit separater Steuereinheit, die mit einer variablen Anzahl an Akkus betrieben werden kann. Ein entsprechendes Feld für die Akku-Fixkosten wäre sinnvoll, um die Amortisation genauer berechnen zu können.

**Comment by nick81nrw** [comment]
Die gesamte Amortisationsrechnung ist sehr rudimentär umgesetzt. Auch jede Speichergröße hat unter Umständen andere Kosten. Fixkosten könntest du auch in die PV Installationskosten einrechnen. Ansonsten mit Eigenverbrauch und Einspeisung in Excel weiterrechnen
