### ISSUE TITLE
Fehler in der Berechnung der Amortisation

### ISSUE THREAD

**Issue by kriede** [nick81nrw/PVTools#14]
Ohne Akku ist in dieser Zeile `size == 1` und so wird ein Promille der Speicherkosten pro kWh zu viel berechnet. Das wird in vielen Fällen kaum auffallen, in Ausnahmefällen könnte es relevante Effekte hervorrufen.

https://github.com/nick81nrw/PVTools/blob/2cca35b608c1c9cfd6bd189f959b499b719a860c/pvtools/pages/index.vue#LL502C30-L502C30

**Comment by kriede** [comment]
Auch auf die Wert in anderen Werte ohne Batterie hat das Auswirkungen, weil in der Simulation ohne Batterie mit einer Batterie der Größe 1Wh gerechnet wird.

Gibt es einen Grund, warum hier mit `size = 1` statt mit `size = 0` gerechnet wird? Ich habe das mal an allen relevanten Stellen auf `size = 0` umgestellt und keine Fehler erkennen können, außer den oben genannten Abweichungen im Promille-Bereich.

**Comment by nick81nrw** [comment]
Ist korrigiert. Es steht zwar weiterhin 1Wh drin, aber der Wert ist gleich min/max Kapazität. Ich verhindere damit nur DIV/0 Fehler (die sicherlich auch anders gelöst werden könnten)
