### ISSUE TITLE
download der berechneten lastgänge zur weiteren Analyse in CSV 

### ISSUE THREAD

**Issue by mar-hec** [nick81nrw/PVTools#18]
Ich würde gerne zur weiteren Analyse (z.B. um meinen Verbrauch entsprechend anzupassen oder zu steuern) die berechneten Lastgänge (1h oder 15min Auflösung) in einer CSV-Datei herunterladen können. z.B. mit folgenden Spalten:
* Zeitpunkt,
* Verbrauch
* PV-Erzeugung
* Netzbezug
* Netzeinspeisung
* Laden
* Entladen
* Speicherstand

Wäre das möglich?

**Comment by nick81nrw** [comment]
Hey,
ja, das müsste schon funktionieren, zumindest Stundenweise, denn die PV-Erträge bekomme ich von PVGis nur stundenweise. 
Das müsste dann aber je Speichergröße herunterladbar sein, denn diese Werte sind ja je nach Akkugröße unterschiedlich. 
Gib mir etwas Zeit, ich muss mir das mal ansehen.

**Comment by mar-hec** [comment]
Hey cooles Tool übrigens. Mit so einer schnellen Reaktion habe ich gar nicht gerechnet. Respekt.

Klar. Du hast Recht. Der Button zum Herunterladen wäre wohl am besten in den Ergebnisdetails aufgehoben, da wo auch das Balkendiagramm zu finden ist. Jede Zeile hat ja ihre eigenen Lastgänge.

Danke.

**Comment by nick81nrw** [comment]
Ist

**Comment by nick81nrw** [comment]
Ist übrigens erledigt. Du kannst für jkede Speichergröße den Stundenverlauf/Berechnung per csv herunterladen
